In [1]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

# Load image as a numpy array
image = np.array([[10,20,30],[45,55,60],[75,48,49]])



# Create a directed graph
G = nx.DiGraph()

# Add nodes for each pixel
for i in range(image.shape[0]):
    for j in range(image.shape[1]):
        node_id = (i, j)
        node_value = image[i,j]
        G.add_node(node_id, value=node_value)

# Connect neighboring pixels with directed edges and add weights
for i in range(image.shape[0]):
    for j in range(image.shape[1]):
        source_id = (i, j)
        for di, dj in [(-1, 0), (1, 0), (0, -1), (0, 1),(-1,-1),(-1,1),(1,-1),(1,1)]:
            # Check if neighbor is within image boundaries
            if i+di >= 0 and i+di < image.shape[0] and j+dj >= 0 and j+dj < image.shape[1]:
                target_id = (i+di, j+dj)
                source_value = G.nodes[source_id]["value"]
                target_value = G.nodes[target_id]["value"]
                weight = (target_value - source_value)
                if weight< 0:
                    weight = 0 
                G.add_edge(source_id, target_id, weight=weight)


adj_matrix = nx.to_numpy_matrix(G)
# Show adjacency matrix
print(adj_matrix)


# pos = {node_id: node_id for node_id in G.nodes()}
# edge_weights = [G.edges[edge]["weight"] for edge in G.edges()]
# nx.draw(G, pos, node_size=5, width=0.5, edge_cmap=plt.cm.Greys, edge_vmin=0, edge_vmax=np.max(edge_weights))
# plt.show()

[[ 0. 10.  0. 35. 45.  0.  0.  0.  0.]
 [ 0.  0. 10. 25. 35. 40.  0.  0.  0.]
 [ 0.  0.  0.  0. 25. 30.  0.  0.  0.]
 [ 0.  0.  0.  0. 10.  0. 30.  3.  0.]
 [ 0.  0.  0.  0.  0.  5. 20.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  7. 12. 27.  0.  1.]
 [ 0.  0.  0.  0.  6. 11.  0.  0.  0.]]


In [2]:
# Below, Its not same as in paper

In [3]:
outcloseness = nx.closeness_centrality(G)

# Show results
print('Outcloseness centrality:')
for node, outcloseness_centrality in outcloseness.items():
    print(f'Node {node}: {outcloseness_centrality:.4f}')

Outcloseness centrality:
Node (0, 0): 0.6154
Node (0, 1): 0.7273
Node (0, 2): 0.6154
Node (1, 0): 0.7273
Node (1, 1): 1.0000
Node (1, 2): 0.7273
Node (2, 0): 0.6154
Node (2, 1): 0.7273
Node (2, 2): 0.6154


In [4]:
## The End